DROP DATABASE IF EXISTS todoDB;
CREATE DATABASE todoDB;
USE todoDB;
CREATE TABLE todos (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(511) NOT NULL,
    done BOOLEAN NOT NULL,
    due_date DATE NULL
);